networks:
 expense: {}
volumes:
  mysql:
services:  
  mysql: 
    image: mysql:1.0.0
    networks:
    - expense
    contaniner_name: mysql
    volumes:     
    - mysql:/var/lib/mysql

  backend:
    image: backend:1.0.0
    networks:
    - expense
    container_name: backend
    depends_on: 
    - mysql
  frontend:
     image: frontend:1.0.0
     networks:
     - expense
     container_name: frontend
     depends_on:
     - frontend
     ports:
     - 80:80
 